### ISSUE TITLE
"Unable to import Numpy array from Aubio module (error -1)"

### ISSUE THREAD

**Issue by PhilipBanse** [DrLuke/aubio-beat-osc#3]
Hi! Installed aubio-beat-osc on a Raspberry Pi 4 Model B Rev. 1.5 (latest OS) with 

`pip install aubio-beat-osc
`

When I run 

`aubio-beat-osc
`

or

`aubio`

no matter what option or parameter it shows 

_Unable to import Numpy array from Aubio module (error -1)
Unable to import Numpy umath from Aubio module (error -1)
Segmentation fault_

python 3.9.2
aubio 0.4.9
pyaudio 0.2.13
numpy 1.19.5
python-osc 1.8.1

Any idea? Thanks!

**Comment by DrLuke** [comment]
Hello!

This seems to be an issue with aubio itself on raspberry pi. An easy workaround is to install aubio through the debian package repository:

```
pip uninstall aubio
apt-get install python3-aubio libatlas-base-dev
```
